#!/usr/bin/env python3
"""
Comprehensive Multilingual Training Data Generator
Generates diverse, realistic customer service scenarios for Shona and Ndebele
Target: 15,000+ records per language with balanced intent distribution
"""

import json
import random
from typing import List, Dict, Tuple
from collections import Counter
import os

class MultilingualDataGenerator:
    """Generate diverse training data for customer service intents in multiple languages"""
    
    # ENGLISH VARIATIONS (for reference and training)
    ENGLISH_SCENARIOS = {
        "balance_inquiry": [
            "What is my account balance?",
            "Check my account funds",
            "View my balance",
            "How much money do I have?",
            "What's my current balance?",
            "Can you tell me my account balance?",
            "Show me my available balance",
            "How much is in my account?",
            "What are my current funds?",
            "Tell me my balance please",
            "Check my account",
            "Display my balance",
            "I need to know my account balance",
            "What's my balance?",
            "How much do I have?",
        ],
        "transaction_history": [
            "Show me my transaction history",
            "What transactions did I make?",
            "Display my recent transactions",
            "Can you show me my transaction records?",
            "What have I spent recently?",
            "Show my last 10 transactions",
            "I want to see my transaction history",
            "What are my recent transfers?",
            "Display my payment history",
            "Show me what I've sent",
            "Can I see my transaction list?",
            "What transactions are on my account?",
            "Show my last transactions",
            "I need my transaction records",
            "Display my transfer history",
        ],
        "transfer_money": [
            "How do I transfer money?",
            "Send money to another account",
            "I want to transfer funds",
            "Can I transfer money?",
            "How do I send money?",
            "Transfer funds from my account",
            "I need to send money to a friend",
            "Help me transfer money",
            "How to send funds?",
            "Can I transfer to another bank?",
            "I want to move money to my savings",
            "Help with money transfer",
            "How do I send funds?",
            "Transfer my money",
            "Can I send funds now?",
        ],
        "password_reset": [
            "I forgot my password",
            "How do I reset my password?",
            "Can you reset my pin?",
            "I need to change my password",
            "Password reset please",
            "I can't remember my password",
            "Help me reset my login password",
            "How to reset password?",
            "My password is forgotten",
            "Can I change my pin?",
            "I lost my password",
            "Reset my account password",
            "How do I update my password?",
            "Help with password recovery",
            "I need a new password",
        ],
        "loan_inquiry": [
            "Can I get a loan?",
            "What are your loan products?",
            "How much can I borrow?",
            "Tell me about loans",
            "What's the loan interest rate?",
            "Can I apply for a loan?",
            "What are the loan requirements?",
            "How do I get a loan?",
            "What loans are available?",
            "Am I eligible for a loan?",
            "Tell me about your loan products",
            "What's the loan process?",
            "How long does a loan take?",
            "What are loan fees?",
            "Can you approve a loan for me?",
        ],
        "bill_payment": [
            "How do I pay my bills?",
            "Can I pay my electricity bill?",
            "Pay my water bill",
            "How to settle my bills?",
            "I want to pay my phone bill",
            "Bill payment options",
            "How do I pay utilities?",
            "Can I pay bills through your service?",
            "Pay my bills now",
            "What bills can I pay?",
            "Help me pay my bill",
            "I need to pay my bills",
            "How to pay internet bill?",
            "Can I settle my accounts?",
            "Bill payment process",
        ],
        "mobile_money": [
            "What is mobile money?",
            "How does mobile money work?",
            "Can I use your mobile wallet?",
            "Tell me about mobile money services",
            "How to transfer using mobile money?",
            "Mobile money features",
            "What can I do with mobile money?",
            "How to use mobile money?",
            "Is mobile money safe?",
            "What are the limits on mobile money?",
            "Mobile wallet features",
            "Can I withdraw from mobile money?",
            "How does mobile wallet work?",
            "Tell me about your mobile services",
            "What are the mobile money charges?",
        ],
        "account_statement": [
            "Can I get my account statement?",
            "I need my account statement",
            "Show me my monthly statement",
            "How to download my statement?",
            "Print my account statement",
            "Where is my statement?",
            "I want my statement for the month",
            "Can you email me my statement?",
            "Account statement request",
            "I need statements for tax purposes",
            "How do I get my bank statement?",
            "Send me my statement please",
            "I need a copy of my statement",
            "How to view statements?",
            "Can I get a PDF statement?",
        ],
        "transaction_dispute": [
            "I want to dispute this transaction",
            "This charge is wrong",
            "I didn't make this transaction",
            "Can you investigate this charge?",
            "I was overcharged",
            "This transaction is incorrect",
            "I need to report a fraudulent transaction",
            "Can you help with a disputed charge?",
            "I don't recognize this transaction",
            "This money was taken by mistake",
            "I want to dispute this payment",
            "Can you refund this charge?",
            "This transaction shouldn't have gone through",
            "I need to report unauthorized access",
            "Can you reverse this transaction?",
        ],
        "account_opening": [
            "How do I open an account?",
            "Can I open a new account?",
            "What do I need to open an account?",
            "Tell me about account opening",
            "I want to open a savings account",
            "What's the process for opening an account?",
            "Can I open an online account?",
            "How long does account opening take?",
            "What documents do I need?",
            "Can I open a business account?",
            "Tell me the account opening requirements",
            "How to register for an account?",
            "I want to open a checking account",
            "What accounts are available?",
            "Can I open an account online?",
        ],
        "card_request": [
            "Can I get a debit card?",
            "How do I order a card?",
            "I need a credit card",
            "Can I request a card?",
            "How to get a new card?",
            "My card is damaged",
            "I want to order a replacement card",
            "Can I get a prepaid card?",
            "How long does card delivery take?",
            "What card options do you have?",
            "I need a new debit card",
            "Can I get a virtual card?",
            "Tell me about your card products",
            "How to apply for a card?",
            "When will my card arrive?",
        ],
        "atm_location": [
            "Where is the nearest ATM?",
            "Can you find an ATM for me?",
            "ATM locations near me",
            "Where are your ATMs?",
            "Find me the closest ATM",
            "Which ATM is nearest?",
            "I need an ATM location",
            "Do you have ATMs in my area?",
            "Can I withdraw at any ATM?",
            "Where can I find an ATM?",
            "ATM availability in my city",
            "Nearest cash point location",
            "Where is the ATM?",
            "Can I use other ATMs?",
            "Which ATMs accept my card?",
        ],
        "greeting": [
            "Hello",
            "Hi there",
            "Good morning",
            "Good afternoon",
            "Good evening",
            "Hi, how are you?",
            "Hello, I need help",
            "Hi, can you help?",
            "How are you today?",
            "Good day",
            "Hey there",
            "Howdy",
            "Welcome",
            "Hello there",
            "What's up?",
        ],
        "goodbye": [
            "Goodbye",
            "Bye",
            "See you later",
            "Bye for now",
            "Catch you later",
            "Talk soon",
            "Bye bye",
            "See ya",
            "Until next time",
            "Have a good day",
            "Take care",
            "Thanks, bye",
            "Goodbye, thank you",
            "Cya",
            "Have a nice day",
        ],
        "complaint": [
            "I have a complaint",
            "I'm not satisfied with your service",
            "This is unacceptable",
            "I want to complain about",
            "Your service is poor",
            "I'm frustrated with this",
            "This is a formal complaint",
            "I need to lodge a complaint",
            "The service is not good",
            "I'm not happy with this",
            "Can I file a complaint?",
            "This is disappointing",
            "I have a grievance",
            "Your service let me down",
            "I want to report a problem",
        ],
        "general_inquiry": [
            "I have a question",
            "Can you help me?",
            "I need information",
            "Tell me more about",
            "What do you offer?",
            "Can you explain?",
            "I need help with something",
            "Can you assist me?",
            "I'm looking for information",
            "What can you do for me?",
            "Tell me about your services",
            "Can you help me understand?",
            "I have a question about",
            "Help me please",
            "What's the process for?",
        ],
        "update_profile": [
            "How do I update my profile?",
            "Can I change my details?",
            "I need to update my information",
            "How to change my address?",
            "Can I update my phone number?",
            "I want to change my name",
            "How do I modify my profile?",
            "Can I change my email?",
            "Update my profile information",
            "How to edit my details?",
            "Can I change my personal info?",
            "I need to update my contact",
            "How do I change my settings?",
            "Can I update my account info?",
            "Modify my profile please",
        ],
        "account_closure": [
            "How do I close my account?",
            "Can I close my account?",
            "I want to close my account",
            "What's the account closure process?",
            "Can I deactivate my account?",
            "How to permanently close account?",
            "I'm closing my account",
            "What happens when I close my account?",
            "Can I delete my account?",
            "How long does closure take?",
            "I want to terminate my account",
            "Closure request",
            "Can I stop using this account?",
            "How to cancel my account?",
            "Account termination process",
        ],
        "security_pin": [
            "How do I change my PIN?",
            "I forgot my PIN",
            "Can you reset my PIN?",
            "What's my PIN?",
            "How to set a new PIN?",
            "My PIN is forgotten",
            "Change my security PIN",
            "Reset my PIN please",
            "How do I create a PIN?",
            "Can I change my PIN?",
            "Help with PIN reset",
            "I lost my PIN",
            "New PIN setup",
            "Can you help with my PIN?",
            "Update my PIN",
        ],
        "network_connectivity": [
            "I can't connect to the app",
            "Is the app working?",
            "I have connection issues",
            "The app is slow",
            "Can't log in to the app",
            "Connection error",
            "The website is down",
            "Is there a server issue?",
            "Network problems",
            "Can't access my account",
            "Loading is very slow",
            "The app keeps crashing",
            "Connection timeout",
            "Internet issues",
            "Can't load the page",
        ],
        "mobile_wallet_fees": [
            "What are your fees?",
            "How much do you charge?",
            "What's the transaction fee?",
            "Are there any charges?",
            "Tell me about your fees",
            "What's the fee for transfers?",
            "Do you charge for withdrawals?",
            "Monthly fee information",
            "What fees apply?",
            "How much is the service fee?",
            "Are there hidden charges?",
            "What are the wallet fees?",
            "Fee structure",
            "What do you charge for?",
            "Tell me the costs",
        ],
        "branch_location": [
            "Where is your nearest branch?",
            "What's your branch address?",
            "Do you have a branch in my city?",
            "Find me a branch",
            "Where can I visit?",
            "Branch locations",
            "What's your office address?",
            "Do you have branches nationwide?",
            "Which branches are open?",
            "Where's the closest branch?",
            "Branch hours?",
            "Can I visit you in person?",
            "What cities have branches?",
            "Physical location of bank",
            "Where is your headquarters?",
        ],
        "escalation_request": [
            "I need to speak to a manager",
            "Can I speak to a supervisor?",
            "I want to escalate this",
            "Can I talk to a senior agent?",
            "This needs manager attention",
            "Escalate my issue",
            "I need help from a specialist",
            "Can I speak to someone else?",
            "This is urgent",
            "I want to escalate",
            "Connect me to a manager",
            "This needs escalation",
            "Can you transfer me?",
            "I need senior support",
            "Escalate this request please",
        ],
    }
    
    # SHONA TRANSLATIONS AND VARIATIONS
    SHONA_SCENARIOS = {
        "balance_inquiry": [
            "Ndiani mari yangu?",
            "Cheka mari yangu yepakumikirira",
            "Ndipei balance yangu",
            "Mari yangu yepakumikirira nguruve?",
            "Ndipei mari yangu yazvino",
            "Unganditsanangura balance yangu?",
            "Cheka mari yangu",
            "Mari yangu yava mangani?",
            "Ndimukumbire balance yangu",
            "Ndinoda kuzoona mari yangu",
            "Cheka zvamari zvandine",
            "Ndipei account balance yangu",
            "Cheka account yangu",
            "Mari yangu ino?",
            "Ndinoda kuzoona balance yangu",
            "Ndipei summary yeaccount yangu",
            "Cheka account yangu ino",
            "Ndiudze mari yangu yazvino",
            "Account yangu ine mari mangani?",
            "Ndipei details yeaccount yangu",
        ],
        "transaction_history": [
            "Ndipei history yematranzaction angu",
            "Mari yandaituma kupi?",
            "Cheka matranzaction angu",
            "Ndipei rondedzero yezvandatumira",
            "Zvandatumira nguva dzinopfuura",
            "Cheka zvandataura/ndakabhadhura",
            "Ndinoda kuzoona matranzaction angu",
            "Ndipei transaction records angu",
            "Matranzaction angu edzimapfuura?",
            "Cheka mari yandataura",
            "Ndipei history yesendz angu",
            "Zvandatumira kwazvandakaitumira?",
            "Transaction records yangu?",
            "Cheka zvamari zvandakatuma",
            "Ndipei list yezvandakataura",
            "Matranzaction angu enjoro dzinopfuura?",
            "Cheka zvandabhadhura",
            "Ndipei history yeaccount yangu",
            "Zvandakatuma mangani?",
            "Cheka remittance history angu",
        ],
        "transfer_money": [
            "Ndingakaita sei transfer?",
            "Ndinoda kukatuma mari",
            "Ndingakataura mari kupi?",
            "Nganditsanangura transfer",
            "Ndinoda kutuma mari kudzimba yangu",
            "Ndingakabhadhura sei mukundirana?",
            "Tumai mari yangu",
            "Ndingakataura mari kumusha kwangu?",
            "Tichange tutume mari",
            "Ndinoda transfer yemaunit",
            "Ndingakataura mari kunzira?",
            "Chii process yetransfer?",
            "Ndinoda kutuma mari kuna shamwari yangu",
            "Ndingakaita sei transfer yasangano?",
            "Tumai mari ino kuaccount yangu",
            "Ndinoda kukatuma mari kukunze",
            "Ndingakabhadhura mari seiko?",
            "Tumai account yangu",
            "Ndinoda transfer nhindi ino",
            "Katuma mari yangu kumbini",
        ],
        "password_reset": [
            "Ndakakoseseka password yangu",
            "Ndinoda kuseta password yatsva",
            "Ndakasikwa password yangu",
            "Reset password yangu",
            "Ndinoda kuchange password",
            "Ndakakoseseka PIN yangu",
            "Ndapihwa kana password yangu?",
            "Ndinoda PIN yatsva",
            "Iwe mhangeri reset yangu",
            "Password yangu inangirira seiko?",
            "Ndakasikwa security PIN yangu",
            "Ndipei password yatsva",
            "Chii process yetransaction?",
            "Reset PIN yangu ngakumbira",
            "Ndakakoseseka kuvhura account",
            "Password yangu haisi kusechana",
            "Kunzira yekuseta password yatsva",
            "Ndakasikwa login credentials yangu",
            "Ndinoda kuchange PIN",
            "Reset account yangu",
        ],
        "loan_inquiry": [
            "Ndingakakopa mari?",
            "Ndipei zvemarupiro yemari yakopwa",
            "Ndingakakopa mangani?",
            "Zvemari yakopwa unganditsanangura sei?",
            "Ndinoda kurapidza chi loan",
            "Ndingazvikurumidza here?",
            "Mari yakopwa inotora nguva yangani?",
            "Ndingakakopa sei?",
            "Chii requirements yemari yakopwa?",
            "Ndingakora here muenzanzo ine?",
            "Loan products andinayo?",
            "Zveringirano yemari yakopwa?",
            "Ndinoda kurapidza muhibheru",
            "Ndingakakopa mari yekumba?",
            "Chii interest rate yemari yakopwa?",
            "Ndinoda loan yezvikoro",
            "Ndinoda kurapidza mausu mavakerekere",
            "Undapihwa kachirevo chari?",
            "Ndingakora business loan?",
            "Zvemududziro yemari yakopwa?",
        ],
        "bill_payment": [
            "Ndingabhadhura sei bili yangu?",
            "Ndinoda kubhadhura mbazi yangu",
            "Bhadzurai stima yangu",
            "Bhadzurai mwater yangu",
            "Bilini yangu ingabhadhurwai sei?",
            "Ndinoda kubhadhura phone bill",
            "Bhadzurai internet yangu",
            "Ndinoda kubhadhura taxes",
            "Bhadzurai school fees",
            "Ndinoda kubhadhura rent",
            "Bhadzurai newe ngakumbira",
            "Bili yamhasi ino?",
            "Ndingabhadhura utilities sei?",
            "Ndinoda kubhadhura matanho angu",
            "Bhadzurai magirifo angu",
            "Bili yangu yava mangani?",
            "Ndinoda kubhadhura mausu angu",
            "Ndingabhadhura mukunzira sei?",
            "Bhadzurai munhu wangu",
            "Ndingasunungura debts yangu?",
        ],
        "mobile_money": [
            "Chii mobile money?",
            "Mobile money inoshandisa sei?",
            "Ndingadaro sei ecocash?",
            "Unganditsanangura ecocash kunzira dzinosarudzika?",
            "Chii zvemobile wallet?",
            "Ecocash mari inoitwa sei?",
            "Mobile services yenyu?",
            "Ndinoda kukosha mobile money",
            "Ndingashandisa mobile payment?",
            "Chii limits yemobile money?",
            "Charges yemobile money?",
            "Security yemobile money inovakakanaka here?",
            "Ndinoda kuita transfer yamobile",
            "Ecocash services yenyu?",
            "Ndinoda kukosha ecocash",
            "Ndingawidraw sei kumobile wallet?",
            "Zveringirano yemobile?",
            "Ndingakosha kupi ecocash?",
            "Ecocash account yatsva?",
            "Ndingakora ecocash services?",
        ],
        "account_statement": [
            "Ndingakuona statement yangu?",
            "Ndipei account statement yangu",
            "Ndinoda kuona statement yenyu",
            "Statement yangu yezvimina zvipfuura",
            "Ndipei PDF statement yangu",
            "Statement yangu inofanira kunyora sei?",
            "Email statement yangu",
            "Ndinoda statement yetax",
            "Chii process yekuget statement?",
            "Statement yangu ine chii?",
            "Download statement yangu",
            "Ndinoda statement yekunze",
            "Statement yangu yazvino?",
            "Kunzira yekuprint statement",
            "Ndipei statement yezvnhamba dzinopfuura",
            "Statement yangu inotora nguva yanani?",
            "Ndinoda kukosha statement",
            "Cheki statement yangu",
            "Account activity yangu?",
            "Ndipei history yangu yefull",
        ],
        "transaction_dispute": [
            "Ndinoda kupikisa transaction ino",
            "Mari ino yaikohwichitai sei?",
            "Ndakasadya mari ino",
            "Ndinoda kumatanisira transaction ino",
            "Batikira mari ino yaikohwichitai",
            "Ndakasadya kurewa ino",
            "Ndinoda kurapidza mhaka yemari",
            "Mari ino yaikuisa sei?",
            "Ndakasadya batikira transaction ino",
            "Mhaka yemari ino?",
            "Ndinoda kuzoona mari ino yadzokwa",
            "Ndikupe mari ino",
            "Yaikohwichitai chizvarwa ino",
            "Mhaka yezvinokeronya?",
            "Ndakasadya kuhwira ino",
            "Revation yetransaction?",
            "Ndinoda investigation yemari ino",
            "Ndinoda kurangarira transaction ino",
            "Mari ino yaikohwidye batikira",
            "Ndinoda kurapidza chizvarwa ino",
        ],
        "account_opening": [
            "Ndingabukie account yatsva?",
            "Ndipei account yatsva",
            "Chii process yekubukie account?",
            "Ndinoda kubukie savings account",
            "Chii documents ndinodikanwa?",
            "Account yatsva inotora nguva yanani?",
            "Ndingabukie online account?",
            "Ndingabukie business account?",
            "Chii conditions zveaccount?",
            "Ndinoda kukosha account",
            "Ndipei account details",
            "Kunzira yekubukie account?",
            "Ndinoda kuregistra account yatsva",
            "Chii advantages yeaccount?",
            "Ndingakora checking account?",
            "Account yatsva yakanaka sei?",
            "Mhando yemaaccount?",
            "Ndakoda kubukie account yangu",
            "Chii madzikomo ekubukie?",
            "Ndinoda account yechild",
        ],
        "card_request": [
            "Ndingakora debit card?",
            "Ndinoda card yatsva",
            "Card yangu yakaputsika",
            "Ndipei card yeringirani",
            "Chii process yekukora card?",
            "Ndinoda credit card",
            "Card yangu yaimbirira",
            "Chii matzara ecard?",
            "Card yatsvatsva inotora nguva yanani?",
            "Ndingakora prepaid card?",
            "Card yangu yaiswa kupi?",
            "Virtual card ndingakora?",
            "Ndipei card yeteacher",
            "Card yangu yairasa",
            "Chii mhando yecard?",
            "Ndakoda kuzviputsa card",
            "Card yangu inofanira kuva?",
            "Ndinoda card yevashandi",
            "Card replacement process?",
            "Ndingakora international card?",
        ],
        "atm_location": [
            "Ndipi ATM isina kure?",
            "ATM kupi ndipapo?",
            "Ndipei ATM location",
            "ATM ipi iri padandemutande?",
            "Ndinoda ATM yepakupi?",
            "ATM kupi kubasa?",
            "Ndipei address yeATM",
            "Muchinini chii kune ATM?",
            "ATM yakapo ku hours yanani?",
            "Ndingashandisa card kuATM yose?",
            "ATM paya kupi?",
            "Ndipi ATM isina kuita kuzivisa?",
            "ATM kupi panguo ino?",
            "Sango lini ATM?",
            "Ndinoda ATM yepakupi",
            "ATM kupi pamusika?",
            "Ndipei ATM yepabasa",
            "ATM iri paschool?",
            "Ndinoda ATM yedandemutande",
            "ATM kupi pashoping centre?",
        ],
        "greeting": [
            "Mangwanani",
            "Mwayi",
            "Masikati",
            "Magare",
            "Howzit",
            "Yo",
            "Ndiani wake?",
            "Jambai",
            "Kwabayana?",
            "Mutsangsana sei?",
            "Ndapota",
            "Hie",
            "Ay",
            "Zvakaoma?",
            "Kutenda here?",
            "Kusvika sei?",
            "Murambiko",
            "Apa ndo",
            "Ah",
            "Zuva rose",
        ],
        "goodbye": [
            "Chidzokero",
            "Dzai",
            "Bye",
            "Mwasakata",
            "Zuva nako",
            "Kuonana",
            "Tete",
            "Nyarara nako",
            "Ndokupfupika",
            "Zuva rose",
            "Kwahuru",
            "Tunzwe",
            "Hameno",
            "Zvakaoma",
            "Tadza",
            "Kuonera",
            "Chokwadi",
            "Mutsangsana",
            "Ndizodai",
            "Wangu zvinemo",
        ],
        "complaint": [
            "Ndinoda kupikirisa",
            "Service yenyu haizoitiki",
            "Ndinoda kurapidza mhaka",
            "Ndakasadya batsirwa",
            "Kuzipisa kweservice",
            "Hazvina kushandika",
            "Ndakasadya kusevenzwa",
            "Mufananidzo wake hauwanikwa",
            "Ndinoda kuzipisa servisi",
            "Service haisi nzira",
            "Ndakasadya kupikirisa",
            "Zvakaipa zvino",
            "Ndakasadya kushanda",
            "Ndinoda zuva rega-rega",
            "Service dzinodaharira",
            "Ndinoda kurapidza",
            "Ndakasadya kupikirisa",
            "Ndiyo complaint",
            "Ndinoda manager",
            "Zvakaipa here",
        ],
        "general_inquiry": [
            "Ndinoda kubudirira",
            "Ungandibatsira?",
            "Ndinoda knowledge",
            "Unditsanangure sei?",
            "Chii unogona kuita?",
            "Ndipei info",
            "Ndikumbire ruzivo",
            "Ndinoda kuziva",
            "Unganditsanangura?",
            "Chii zvepamwe?",
            "Ndinoda kuburikidza",
            "Services yenyu chii?",
            "Ndipei mapurogiramu",
            "Ndinoda kuzoona",
            "Ndibatsire",
            "Chii ndinoziva here?",
            "Ungandipei details?",
            "Ndikumbire sachema",
            "Ndinoda kuburikidza",
            "Details chii?",
        ],
        "update_profile": [
            "Ndingachange details yangu?",
            "Ndipei kuvhura yangu",
            "Ndinoda kuchange address",
            "Ndingachange phone number?",
            "Phone number yangu yatsva",
            "Ndipei email yatsva",
            "Ndipei profile yangu",
            "Ndingachange dzina langu?",
            "Email yangu yaitowaka",
            "Ndinoda kuchange password",
            "Details yangu chii?",
            "Ndinoda kuchange madata",
            "Kuzviputsa vanhu?",
            "Ndingachange gender?",
            "Ndipei kuvhura yangu",
            "Ndingachange all details?",
            "Profile yangu yatsva",
            "Madata yangu yatowa",
            "Ndinoda kuchange everything",
            "Update yangu yatsva",
        ],
        "account_closure": [
            "Ndingavhara account yangu?",
            "Ndinoda kusvika account",
            "Chii process yekuvhara account?",
            "Ndingavhara pakupfuura?",
            "Account yangu yavharwe",
            "Ndinoda kusvika account yangu",
            "Vharire account yangu",
            "Account yangu inoshandwa sei?",
            "Ndikophe account yangu",
            "Chii kunenge chavhara account?",
            "Ndinoda kusiya account",
            "Vhara yangu",
            "Ndipei kunenge chavhara",
            "Ndakoda kusvika",
            "Account yangu yavharwe sei?",
            "Ndinoda kusiya",
            "Closure yatakutoka",
            "Ndingavhara kare?",
            "Delete account yangu",
            "Account yavharwe here?",
        ],
        "security_pin": [
            "Ndakakoseseka PIN yangu",
            "Ndingachange PIN yangu?",
            "Ndipei PIN yatsva",
            "PIN yangu yaiwakichitai?",
            "Reset PIN yangu",
            "Chii PIN yangu?",
            "PIN yatsva inodiwa",
            "PIN yangu yainofadza",
            "Ndakasikwa PIN",
            "Ndinoda PIN yatsva",
            "PIN yangu yatowa",
            "Ndipei PIN",
            "PIN yangu haisiti",
            "Ndakakoseseka PIN",
            "PIN yatsva here",
            "PIN yangu yava mangani?",
            "Ndakakoseseka security",
            "PIN yatsva",
            "Security PIN yangu",
            "Ndingachange security?",
        ],
        "network_connectivity": [
            "Ndinogona kukosha kumhuri?",
            "Mhuri haisi kushandika",
            "Internet haisiti",
            "App yakaputsika",
            "Ndinogona kuwaya account?",
            "Loading inoita slow",
            "Ndinogona kulovha?",
            "Mhuri yava pasi",
            "Network error",
            "Can't access",
            "Kuchinini chii?",
            "Internet inofadza",
            "App inokuromba",
            "Ndinogona kuiza?",
            "Server yava pasi",
            "Connection issue",
            "Ndinogona kukosha?",
            "Website yava pasi",
            "Mhuri haina kushandika",
            "Speed inobadza",
        ],
        "mobile_wallet_fees": [
            "Ndipei charges",
            "Mari yatora mangani?",
            "Chii fees?",
            "Ndipei transaction fee",
            "Charges yemakit?",
            "Pane fees?",
            "Ndipei withdrawal fee",
            "Transfer fee chii?",
            "Fee yetransaction?",
            "Monthly fees pane here?",
            "Chii hidden charges?",
            "Service fee yava mangani?",
            "Ndipei cost?",
            "Charges yepakupi?",
            "Fees yeve wallet?",
            "Ndipei price list",
            "Mari yangu yatorwa?",
            "Chii payment?",
            "Chii amount?",
            "Ndingabhadhura mangani?",
        ],
        "branch_location": [
            "Ndipi branch isina kure?",
            "Branch kupi?",
            "Address yeoffice?",
            "Pane branch paya?",
            "Muchinini chii branch?",
            "Branch kupi pebasa?",
            "Ndipei office address",
            "Branch yepagwekugure?",
            "Zvapo kupi?",
            "Ndipei location yepamwe",
            "Branch kupi padandemutande?",
            "Office kupi?",
            "Ndipei branch details",
            "Ndipi branch yepakupi?",
            "Pane office paya?",
            "Ndipei headquarters",
            "Branch kupi musikiti?",
            "Ndipi branch iri pashungu?",
            "Ndipei contact address",
            "Branch hours chii?",
        ],
        "escalation_request": [
            "Ndinoda kuvawa manager",
            "Ndipei supervisor",
            "Ndakoda kusvika paneshure",
            "Ndapikise nyaya ino",
            "Ndinoda specialist",
            "Escalate mhaka yangu",
            "Ndakoda kusvika panyore",
            "Mhaka ino inodiwa specialist",
            "Ndipei senior agent",
            "Ndakoda kupia",
            "Nyaya ino inofanira manager",
            "Urgent nayo",
            "Ndakoda kusvika paneshure",
            "Transfer naye",
            "Ndakoda senior support",
            "Ndiyo escalation",
            "Specialist yenyu",
            "Ndakoda kupia paneshure",
            "Urgent consultation",
            "Ndakoda kupia mangwanani",
        ],
    }
    
    # NDEBELE TRANSLATIONS AND VARIATIONS
    NDEBELE_SCENARIOS = {
        "balance_inquiry": [
            "Unganditse umnotho wami?",
            "Chekela ama-account wami",
            "Ngandibele ingcediso yami",
            "Ngandibele imali enhle yami",
            "Unganditse imali yami idlala kangakanani?",
            "Imali yami yaliboni mangaphansi?",
            "Chekela ingcediso yama-account",
            "Ingcediso yami idlala kangakanani?",
            "Ngandi-check ingcediso yami?",
            "Imali yami idlala kangakanani phambi nesikhathi?",
            "Ungandite ingcediso yami idlala kangakanani?",
            "Ndifuna ukwazi imali yami",
            "Chekela ingcediso yama-account yami",
            "Imali yami idlala kangakanani?",
            "Ungandibele umnotho wami idlala kangakanani?",
            "Chekela ingcediso yami nhle",
            "Imali yami idlala mangakanani?",
            "Ndifuna ukwazi ngal-balance wami",
            "Ungandibele imali yhile yami?",
            "Imali yami yaliboni masinya?",
        ],
        "transaction_history": [
            "Ndifuna ukwazi izinto ezalidlala",
            "Ungandibele izililo zami?",
            "Chekela imali esalidlela",
            "Izililo zami zelibulele",
            "Ungandibele imali endithlela?",
            "Chekela izinto endidihlela",
            "Ndifuna ukwazi okudalwe ngezililo",
            "Izililo zami zithini?",
            "Ungandibele izinto endidudluze?",
            "Chekela ama-transaction wami",
            "Imali sendithlela kuhle",
            "Ungandibele izililo zami zesukela emuva?",
            "Ndifuna ukwazi izililo zami zonke",
            "Chekela izinto esalikhona",
            "Izililo zami zesililo sami?",
            "Ungandibele okubaluleke kunamuhla?",
            "Chekela okudalwe ngaminyakazo",
            "Imali sendithwesile kuhle?",
            "Izililo zami zahlanganiswa?",
            "Ngandi-report izililo zami?",
        ],
        "transfer_money": [
            "Ngingakwazi ngani ukukhuluma imali?",
            "Ndifuna ukukhuluma imali",
            "Unganditsanangura ukunikeza imali?",
            "Nginikeze imali emuntumweni wami",
            "Imali yami ithunyelwile kangakanani?",
            "Ngingakwazi ukukhuluma imali kwebhanki?",
            "Ukukhuluma imali kumuntu omunye",
            "Ndifuna ukukhuluma imali yama-unit",
            "Ungandibele inkhombandlela yokunenza okuningi?",
            "Ukukhuluma imali kumnumzane wami",
            "Ngingakwazi ukukhuluma imali?",
            "Imali yami ithunyelwile lungile",
            "Unganditsanangura okukhulumayo",
            "Ndifuna ukukhuluma imali yama-emergency",
            "Ukukhuluma imali kunumzane wami",
            "Imali yami ithunyelwile kuhle",
            "Ngindi-transfer imali?",
            "Ungandibele okukhulumayo?",
            "Ndifuna ukukhuluma imali yeshukela",
            "Imali yami idlondlobele kuhle?",
        ],
        "password_reset": [
            "Ndikhohlwe i-password yami",
            "Ngikwazi ngani ukukhela i-password?",
            "Ngindise i-password yami esha",
            "Ungandibele inkhombandlela yokunenza kabusha?",
            "I-PIN yami idlala kuphi?",
            "Ndikhohlwe i-PIN yesiphiwo",
            "Ngiphakamisele i-password esha",
            "Unganditsanangura ukunikeza i-password esha?",
            "Ndikhohlwe amakholodi ami",
            "Ngindulule i-password yami",
            "Ungandibele inkhombandlela yokunenza kabusha?",
            "I-PIN yami idlala kuphi?",
            "Ndikhohlwe i-security PIN yami",
            "Ngiphakamisele i-password esha",
            "Unganditsanangura ukudulula i-password?",
            "Ndifuna ukukhela i-password esha",
            "I-password yami idlala kuphi?",
            "Ngindise i-PIN yami esha",
            "Ungandibele inkhombandlela yokudulula i-password?",
            "Ndikhohlwe i-login yami?",
        ],
        "loan_inquiry": [
            "Ngingakwazi ngani okuboleke imali?",
            "Ungandibele ngamaloan engu?",
            "Ndifuna okuboleke imali",
            "Imali endingayiboleka idlala kangakanani?",
            "Ungandibele amaloan amakhulu?",
            "Inzuzo yobuboleki idlala kangakanani?",
            "Ngingakwazi okuboleke imali yasekhaya?",
            "Unganditsanangura okuboleka imali?",
            "Ndifuna okuboleke emali yezemoto",
            "Ungandibele inkhombandlela yobuboleki?",
            "Amaloan akuthini?",
            "Ngingakwazi okuboleke ngezikwelethi?",
            "Ungandibele umnotho wobuboleki?",
            "Ndifuna okuboleke emali yeshukela",
            "Unganditsanangura amaloan amakhulu?",
            "Inzuzo yobuboleki idlala kangakanani?",
            "Ngingakwazi okuboleke imali yama-business?",
            "Ungandibele inkhombandlela yobuboleki?",
            "Amaloan akuthini kunamuhla?",
            "Ndifuna okuboleke imali esha?",
        ],
        "bill_payment": [
            "Ngingakwazi ngani okurhoxisa imikhelo?",
            "Ndifuna okurhoxisa ibhele lami",
            "Ungandibele inkhombandlela yokubhejula imilandu?",
            "Ibhele lam libhejulwe lungile",
            "Ngindise imilandu yami",
            "Unganditsanangura ukubhejula amakhodi?",
            "Ndifuna okurhoxisa ibhele lika-electricity",
            "Ibhele l-water lidlala kangakanani?",
            "Ungandibele inkhombandlela yokubhejula?",
            "Ndifuna okurhoxisa ibhele lika-phone",
            "Ibhele lika-internet lidlala kangakanani?",
            "Ngindise imilandu yemuzi wami",
            "Unganditsanangura okurhoxisa ibhele?",
            "Ndifuna okurhoxisa ibhele lika-rent",
            "Ibhele l-tax lidlala kangakanani?",
            "Ungandibele inkhombandlela yokubhejula?",
            "Ndifuna okurhoxisa ibhele lama-rates",
            "Ibhele l-school fee lidlala kangakanani?",
            "Ngindise ibhele lami",
            "Ungandibele inkhombandlela yokubhejula?",
        ],
        "mobile_money": [
            "Chii i-mobile money?",
            "Ungandibele ngal-ecocash?",
            "Ngingakwazi ngani okusingatha imali yomuntu?",
            "Unganditsanangura i-mobile wallet?",
            "Ndifuna okusingatha imali ka-mobile",
            "Ecocash isetshenziswa kangakanani?",
            "Ungandibele ngamasevisi ka-mobile?",
            "Ngingakwazi okuboleke emali ka-mobile?",
            "Unganditsanangura umnotho womi wa-mobile?",
            "Ndifuna okulingana noma-ecocash",
            "Ecocash lidlala lungile?",
            "Ungandibele inkhombandlela yokunenza kahle?",
            "Ndifuna okulingana noma-mobile payment",
            "Unganditsanangura amasevisi kama-mobile?",
            "Imali endingayiboleka idlala kangakanani?",
            "Ungandibele ngamalimite ka-mobile?",
            "Ndifuna okusingatha imali ka-mobile",
            "Ecocash ayasulula kabusha?",
            "Unganditsanangura umnotho womi wa-mobile?",
            "Ndifuna okulingana noma-ecocash kabusha?",
        ],
        "account_statement": [
            "Ngingakwazi ngani ukukuona isithelelo sami?",
            "Ungandibele isithelelo sami?",
            "Ndifuna isithelelo sami senyanga",
            "Unganditsanangura isithelelo sami?",
            "Isithelelo sami sidlala lungile?",
            "Ngindise i-PDF isithelelo sami",
            "Ungandibele inkhombandlela yokukuona isithelelo?",
            "Ndifuna isithelelo sami sezikwelethi",
            "Unganditsanangura isithelelo sami?",
            "Isithelelo sami sidlala kangakanani?",
            "Ngindowaniswele isithelelo sami",
            "Ungandibele inkhombandlela yokuthela isithelelo?",
            "Ndifuna i-email isithelelo sami",
            "Unganditsanangura isithelelo sami?",
            "Isithelelo sami sidlala kumuntu?",
            "Ngindise isithelelo sami sekilasi",
            "Ungandibele inkhombandlela yokuthawula isithelelo?",
            "Ndifuna isithelelo sami sabanye",
            "Unganditsanangura isithelelo sami?",
            "Isithelelo sami sidlala kabusha?",
        ],
        "transaction_dispute": [
            "Ndifuna okuphikisana nomsebenzeli",
            "Ungandibele inkhombandlela yokuthwala umkhiphe?",
            "Imali yami idlala lungile",
            "Ndikhohlwe imali yami",
            "Unganditsanangura umkhiphe wami?",
            "Okudalwe kwami akukulungile",
            "Ndifuna okuphikisana nokudalwe",
            "Ungandibele inkhombandlela yokuthwala umkhiphe?",
            "Imali yami idlalwe kahle",
            "Ndikhohlwe okudalwe kwami",
            "Unganditsanangura umkhiphe wami?",
            "Ndifuna okuphikisana nomsebenzeli",
            "Ungandibele inkhombandlela yokudlula umkhiphe?",
            "Imali yami idlala lungile",
            "Ndikhohlwe imali yami",
            "Unganditsanangura umkhiphe wami?",
            "Okudalwe kwami akukulungile",
            "Ndifuna okuphikisana nokudalwe",
            "Ungandibele inkhombandlela yokuthwala umkhiphe?",
            "Imali yami idlalwe kahle",
        ],
        "account_opening": [
            "Ngingakwazi ngani okubukulula i-account esha?",
            "Ungandibele inkhombandlela yokuvula i-account?",
            "Ndifuna okubukulula i-savings account",
            "Unganditsanangura inkhombandlela yokuvula?",
            "I-account eshasokukhela kangakanani?",
            "Ngindise i-account esha",
            "Ungandibele inkhombandlela yokuvula i-account?",
            "Ndifuna okubukulula i-business account",
            "Unganditsanangura inkhombandlela yokuvula?",
            "I-account eshasokukhela umbali?",
            "Ngindi-register i-account esha",
            "Ungandibele inkhombandlela yokuvula i-account?",
            "Ndifuna okubukulula i-student account",
            "Unganditsanangura inkhombandlela yokuvula?",
            "I-account eshasokukhela indlela?",
            "Ngindise i-account esha",
            "Ungandibele inkhombandlela yokuvula i-account?",
            "Ndifuna okubukulula i-joint account",
            "Unganditsanangura inkhombandlela yokuvula?",
            "I-account eshasokukhela umuzi?",
        ],
        "card_request": [
            "Ngingakwazi ngani okucelula ikhadi?",
            "Ungandibele inkhombandlela yokukela ikhadi?",
            "Ndifuna ikhadi lelekishini lami",
            "Unganditsanangura inkhombandlela yokukela?",
            "Ikhadi elishi lidlala lungile?",
            "Ngindise ikhadi elisha",
            "Ungandibele inkhombandlela yokukela ikhadi?",
            "Ndifuna ikhadi lekhalithi",
            "Unganditsanangura inkhombandlela yokukela?",
            "Ikhadi elishe sidlala kangakanani?",
            "Ngindi-replace ikhadi lami",
            "Ungandibele inkhombandlela yokukela ikhadi?",
            "Ndifuna ikhadi lewadi",
            "Unganditsanangura inkhombandlela yokukela?",
            "Ikhadi elishi lidlala ngani?",
            "Ngindise ikhadi elisha",
            "Ungandibele inkhombandlela yokukela ikhadi?",
            "Ndifuna ikhadi letemane",
            "Unganditsanangura inkhombandlela yokukela?",
            "Ikhadi elishe sidlala kabusha?",
        ],
        "atm_location": [
            "Ngiphe iATM esalandelana?",
            "Ungandibele umbangela we-ATM?",
            "Ndifuna iATM kufuphi nami",
            "Unganditsanangura indawo ye-ATM?",
            "IATM idlala kuphi?",
            "Ngiphe indawo ye-ATM",
            "Ungandibele umbangela we-ATM?",
            "Ndifuna iATM ethaveni",
            "Unganditsanangura indawo ye-ATM?",
            "IATM idlala kufuphi?",
            "Ngiphe iATM eyinhloko",
            "Ungandibele umbangela we-ATM?",
            "Ndifuna iATM esivumelane",
            "Unganditsanangura indawo ye-ATM?",
            "IATM idlala inkhosi?",
            "Ngiphe indawo ye-ATM",
            "Ungandibele umbangela we-ATM?",
            "Ndifuna iATM ethayini",
            "Unganditsanangura indawo ye-ATM?",
            "IATM idlala lokhalakele?",
        ],
        "greeting": [
            "Sawubona",
            "Unjani",
            "Hayi",
            "Yoo",
            "Helele",
            "Molo",
            "Sanibonani",
            "Enkosi",
            "Yakile",
            "Uyabonga",
            "Unjani la",
            "Yebo",
            "Aowa",
            "Jee",
            "Nah",
            "Hey",
            "Yo",
            "Ah",
            "Alright",
            "Fine",
        ],
        "goodbye": [
            "Sala kahle",
            "Bawo",
            "Hlala kahle",
            "Uyosala kahle",
            "Bonana",
            "Lokhu kukhala",
            "Ungethembele kahle",
            "Inkosi ibusise",
            "Bawo nkhosi",
            "Shukela kahle",
            "Kuhambile kahle",
            "Shukela ubungane",
            "Hlala ekhaya",
            "Emoyeni",
            "Bawo mhlobo",
            "Sala ekhaya",
            "Bayete",
            "Kuhambile nkosikazi",
            "Uyobona mhlobo",
            "Shukela kukhuleka",
        ],
        "complaint": [
            "Ndifuna okukhala",
            "Ungandibele inkhombandlela yokukela?",
            "Usebenzeli wami akukulungile",
            "Ndikhohlwe umhlobo wami",
            "Unganditsanangura inkhombandlela?",
            "Usebenzeli wami akayazi",
            "Ndifuna okukhala ngomsebenzeli",
            "Ungandibele inkhombandlela yokukela?",
            "Umshumi wami akukulungile",
            "Ndikhohlwe ibhele lami",
            "Unganditsanangura inkhombandlela?",
            "Isevisi yengu akukulungile",
            "Ndifuna okukhala ngesevisi",
            "Ungandibele inkhombandlela yokukela?",
            "Umuntu wami akukulungile",
            "Ndikhohlwe okudalwe kwami",
            "Unganditsanangura inkhombandlela?",
            "Okudalwe kwami akukulungile",
            "Ndifuna okukhala ngokulungile",
            "Ungandibele inkhombandlela yokukela?",
        ],
        "general_inquiry": [
            "Ndifuna imbuzi",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuzi",
            "Unganditsanangura?",
            "Chii unokuthi?",
            "Ngiphe imininingwane",
            "Ndifuna okuzi ngembuzi",
            "Ungandibele inkhombandlela?",
            "Ndifuna okubuza",
            "Unganditsanangura?",
            "Ngibuze isevisi",
            "Ngiphe imininingwane",
            "Ndifuna okuzi nesevisi",
            "Ungandibele inkhombandlela?",
            "Ndifuna okubuza",
            "Unganditsanangura?",
            "Ngibuze umbuzi",
            "Ngiphe imininingwane",
            "Ndifuna okuzi",
            "Ungandibele inkhombandlela?",
        ],
        "update_profile": [
            "Ngingakwazi ngani okuguqula imininingwane yami?",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuguqula inumber yami",
            "Unganditsanangura inkhombandlela?",
            "Inumber yami idlale esha",
            "Ngindise i-email yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuguqula ibizo lami",
            "Unganditsanangura inkhombandlela?",
            "Ibizo lami lidlale esha",
            "Ngindise indawo yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuguqula imininingwane yami",
            "Unganditsanangura inkhombandlela?",
            "Imininingwane yami idlale esha",
            "Ngindise i-password yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuguqula iprofile yami",
            "Unganditsanangura inkhombandlela?",
            "Iprofile yami idlale esha?",
        ],
        "account_closure": [
            "Ngingakwazi ngani okuvalela i-account yami?",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuvalela i-account yami",
            "Unganditsanangura inkhombandlela?",
            "I-account yami idlale ifolitshe",
            "Ngindise i-account yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuvalela i-account yami",
            "Unganditsanangura inkhombandlela?",
            "I-account yami idlale ifolitshe",
            "Ngindi-delete i-account yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuvalela i-account yami",
            "Unganditsanangura inkhombandlela?",
            "I-account yami idlale ifolitshe",
            "Ngindise i-account yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuvalela i-account yami",
            "Unganditsanangura inkhombandlela?",
            "I-account yami idlale ifolitshe",
        ],
        "security_pin": [
            "Ndikhohlwe i-PIN yami",
            "Ungandibele inkhombandlela yokudulula?",
            "Ndifuna i-PIN esha",
            "Unganditsanangura inkhombandlela?",
            "I-PIN yami idlale esha",
            "Ngindise i-PIN yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuguqula i-PIN yami",
            "Unganditsanangura inkhombandlela?",
            "I-PIN yami idlale esha",
            "Ngindi-reset i-PIN yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna i-PIN esha",
            "Unganditsanangura inkhombandlela?",
            "I-PIN yami idlale esha",
            "Ngindise i-PIN yami",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuguqula i-PIN yami",
            "Unganditsanangura inkhombandlela?",
            "I-PIN yami idlale esha?",
        ],
        "network_connectivity": [
            "Ndinogona okulingana?",
            "Ungandibele inkhombandlela?",
            "Inethiweki ayisebenzeli",
            "Unganditsanangura?",
            "Inkinga yamanethiweki",
            "Ngiphe usizo",
            "Ndinogona okulingana?",
            "Ungandibele inkhombandlela?",
            "Iyintanethi ayisebenzeli",
            "Unganditsanangura?",
            "Inkinga ye-internet",
            "Ngiphe usizo",
            "Ndinogona okulingana?",
            "Ungandibele inkhombandlela?",
            "I-app ayisebenzeli",
            "Unganditsanangura?",
            "Inkinga ye-app",
            "Ngiphe usizo",
            "Ndinogona okulingana?",
            "Ungandibele inkhombandlela?",
        ],
        "mobile_wallet_fees": [
            "Ngiphe izindleko?",
            "Ungandibele inkhombandlela?",
            "Imali yami idlale ngani?",
            "Unganditsanangura inkhombandlela?",
            "Izindleko zami idlale ngani?",
            "Ngiphe imininingwane",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuzi ngezindleko",
            "Unganditsanangura inkhombandlela?",
            "Izindleko zami idlale ngani?",
            "Ngiphe imininingwane",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuzi ngezindleko",
            "Unganditsanangura inkhombandlela?",
            "Imali yami idlale ngani?",
            "Ngiphe imininingwane",
            "Ungandibele inkhombandlela?",
            "Ndifuna okuzi ngezindleko",
            "Unganditsanangura inkhombandlela?",
            "Izindleko zami idlale ngani?",
        ],
        "branch_location": [
            "Ngiphe i-branch esandelana?",
            "Ungandibele umbangela we-branch?",
            "Ndifuna i-branch kufuphi nami",
            "Unganditsanangura indawo ye-branch?",
            "I-branch idlala kuphi?",
            "Ngiphe indawo ye-branch",
            "Ungandibele umbangela we-branch?",
            "Ndifuna i-branch ethaveni",
            "Unganditsanangura indawo ye-branch?",
            "I-branch idlala kufuphi?",
            "Ngiphe i-branch eyinhloko",
            "Ungandibele umbangela we-branch?",
            "Ndifuna i-branch esivumelane",
            "Unganditsanangura indawo ye-branch?",
            "I-branch idlala inkhosi?",
            "Ngiphe indawo ye-branch",
            "Ungandibele umbangela we-branch?",
            "Ndifuna i-branch ethayini",
            "Unganditsanangura indawo ye-branch?",
            "I-branch idlala lokhalakele?",
        ],
        "escalation_request": [
            "Ndifuna okukhuluma nomphathi",
            "Ungandibele inkhombandlela?",
            "Ndifuna umuntu omunye",
            "Unganditsanangura inkhombandlela?",
            "Ndifuna usiko lomuthwali",
            "Ngiphe umphathi",
            "Ungandibele inkhombandlela?",
            "Ndifuna okukhuluma nomukhulu",
            "Unganditsanangura inkhombandlela?",
            "Ndifuna umuntu omunye omkhulu",
            "Ngiphe umphathi",
            "Ungandibele inkhombandlela?",
            "Ndifuna okukhuluma nomuntu onobukhosi",
            "Unganditsanangura inkhombandlela?",
            "Ndifuna usiko lomuthwali",
            "Ngiphe umphathi",
            "Ungandibele inkhombandlela?",
            "Ndifuna okukhuluma nomukhulu",
            "Unganditsanangura inkhombandlela?",
            "Ndifuna umuntu omunye omkhulu?",
        ],
    }

    def __init__(self):
        random.seed(42)  # For reproducibility
        self.intents = list(self.ENGLISH_SCENARIOS.keys())
        
    def generate_dataset(self, language: str, target_size: int = 15000) -> List[Dict]:
        """Generate balanced dataset for specified language"""
        scenarios = self.SHONA_SCENARIOS if language == "sn" else self.NDEBELE_SCENARIOS
        records_per_intent = target_size // len(self.intents)
        dataset = []
        
        for intent in self.intents:
            if intent not in scenarios:
                continue
                
            variations = scenarios[intent]
            generated = 0
            
            while generated < records_per_intent:
                # Use variations from the language
                text = random.choice(variations)
                dataset.append({
                    "text": text,
                    "intent": intent,
                    "language": language
                })
                generated += 1
        
        return dataset
    
    def generate_augmented_scenarios(self, language: str, intent: str, count: int = 50) -> List[str]:
        """Generate additional variations for an intent"""
        scenarios = self.SHONA_SCENARIOS if language == "sn" else self.NDEBELE_SCENARIOS
        if intent not in scenarios:
            return []
        
        base_variations = scenarios[intent]
        augmented = []
        
        # Repeat and vary existing phrases
        for _ in range(count):
            variant = random.choice(base_variations)
            # Apply simple variations
            if random.random() > 0.5 and len(variant.split()) > 1:
                words = variant.split()
                if len(words) > 2:
                    variant = " ".join(words[:-1])  # Drop last word
            augmented.append(variant)
        
        return augmented


def main():
    """Generate and save multilingual training datasets"""
    print("🚀 Starting Multilingual Training Data Generation...")
    print(f"Target: 15,000 records per language with balanced intents\n")
    
    generator = MultilingualDataGenerator()
    
    # Load existing dataset
    existing_path = Path("backend/generated/retraining_dataset_phase4_final_balanced.json")
    existing_data = json.load(open(existing_path)) if existing_path.exists() else []
    print(f"✓ Loaded existing dataset: {len(existing_data)} records")
    
    # Generate new data for Shona and Ndebele
    new_records = []
    
    for lang_code, lang_name in [("sn", "Shona"), ("nd", "Ndebele")]:
        print(f"\n📝 Generating {lang_name} data...")
        lang_data = generator.generate_dataset(language=lang_code, target_size=15000)
        new_records.extend(lang_data)
        print(f"  ✓ Generated {len(lang_data)} {lang_name} records")
    
    # Combine existing and new data
    combined_data = existing_data + new_records
    print(f"\n📊 Combined dataset size: {len(combined_data)} records")
    
    # Remove duplicates while preserving order
    seen = set()
    unique_data = []
    for record in combined_data:
        key = (record["text"].lower().strip(), record["intent"], record["language"])
        if key not in seen:
            seen.add(key)
            unique_data.append(record)
    
    print(f"✓ After deduplication: {len(unique_data)} unique records")
    
    # Check distribution
    from collections import Counter
    by_lang = Counter(r["language"] for r in unique_data)
    by_intent = Counter(r["intent"] for r in unique_data)
    
    print(f"\n📈 Distribution by language:")
    for lang, count in sorted(by_lang.items()):
        print(f"  {lang}: {count:,} records")
    
    print(f"\n📈 Distribution by intent (top 10):")
    for intent, count in by_intent.most_common(10):
        print(f"  {intent}: {count:,} records")
    
    # Save augmented dataset
    output_path = Path("backend/generated/retraining_dataset_multilingual_balanced_v2.json")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(unique_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ Saved augmented dataset to: {output_path}")
    print(f"   Total unique records: {len(unique_data):,}")
    print(f"   Shona: {by_lang.get('sn', 0):,}")
    print(f"   Ndebele: {by_lang.get('nd', 0):,}")


if __name__ == "__main__":
    from pathlib import Path
    main()
