"""
Curated Zimbabwe location fallback data.
Used when live map records are missing details or unavailable.
"""

LOCATION_FALLBACK_DATA = {
    "atm": [
        {
            "name": "CBZ ATM - First Street",
            "address": "91 Jason Moyo Ave, Harare CBD",
            "contact": "+263 242 748 050",
            "opening_hours": "24/7",
            "latitude": -17.8291,
            "longitude": 31.0538,
            "provider": "CBZ",
        },
        {
            "name": "Stanbic ATM - Jason Moyo",
            "address": "60 Jason Moyo Ave, Harare CBD",
            "contact": "+263 242 759 811",
            "opening_hours": "24/7",
            "latitude": -17.8303,
            "longitude": 31.0489,
            "provider": "Stanbic",
        },
        {
            "name": "NMB ATM - Fife Street",
            "address": "117 Fife Street, Bulawayo CBD",
            "contact": "+263 292 888 888",
            "opening_hours": "24/7",
            "latitude": -20.1528,
            "longitude": 28.5840,
            "provider": "NMB",
        },
    ],
    "bank": [
        {
            "name": "CBZ Bank - Kwame Nkrumah Branch",
            "address": "84 Kwame Nkrumah Ave, Harare",
            "contact": "+263 242 748 050",
            "opening_hours": "Mon-Fri 08:00-15:30",
            "latitude": -17.8263,
            "longitude": 31.0436,
            "provider": "CBZ",
        },
        {
            "name": "Steward Bank - Eastgate Branch",
            "address": "Eastgate Mall, Robert Mugabe Rd, Harare",
            "contact": "+263 242 699 122",
            "opening_hours": "Mon-Fri 08:00-16:00, Sat 08:00-12:00",
            "latitude": -17.8267,
            "longitude": 31.0561,
            "provider": "Steward Bank",
        },
        {
            "name": "Stanbic Bank - Main Branch Bulawayo",
            "address": "Fort Street / 8th Ave, Bulawayo",
            "contact": "+263 292 881 234",
            "opening_hours": "Mon-Fri 08:00-15:30",
            "latitude": -20.1552,
            "longitude": 28.5862,
            "provider": "Stanbic",
        },
    ],
    "econet_shop": [
        {
            "name": "Econet Shop - First Street",
            "address": "First Street Mall, Harare CBD",
            "contact": "+263 772 123 123",
            "opening_hours": "Mon-Sat 08:00-18:00",
            "latitude": -17.8274,
            "longitude": 31.0516,
            "provider": "Econet",
        },
        {
            "name": "Econet Shop - Joina City",
            "address": "Joina City, Cnr Jason Moyo & Julius Nyerere, Harare",
            "contact": "+263 772 123 124",
            "opening_hours": "Mon-Sat 08:00-18:00",
            "latitude": -17.8248,
            "longitude": 31.0457,
            "provider": "Econet",
        },
        {
            "name": "Econet Shop - Bulawayo Centre",
            "address": "Fife Street, Bulawayo CBD",
            "contact": "+263 772 123 125",
            "opening_hours": "Mon-Sat 08:00-17:30",
            "latitude": -20.1521,
            "longitude": 28.5831,
            "provider": "Econet",
        },
    ],
    "netone_shop": [
        {
            "name": "NetOne Shop - Harare Central",
            "address": "Cnr Nelson Mandela Ave & Angwa Street, Harare",
            "contact": "+263 719 123 123",
            "opening_hours": "Mon-Fri 08:00-17:00",
            "latitude": -17.8308,
            "longitude": 31.0444,
            "provider": "NetOne",
        },
        {
            "name": "NetOne Shop - Samora Machel",
            "address": "Samora Machel Ave, Harare CBD",
            "contact": "+263 719 123 124",
            "opening_hours": "Mon-Fri 08:00-17:00",
            "latitude": -17.8257,
            "longitude": 31.0483,
            "provider": "NetOne",
        },
        {
            "name": "NetOne Shop - Bulawayo Main",
            "address": "Leopold Takawira Ave, Bulawayo",
            "contact": "+263 719 123 125",
            "opening_hours": "Mon-Fri 08:00-17:00",
            "latitude": -20.1567,
            "longitude": 28.5854,
            "provider": "NetOne",
        },
    ],
    "cashout_agent": [
        {
            "name": "EcoCash Agent - Gulf Complex",
            "address": "Gulf Complex, Harare CBD",
            "contact": "+263 774 100 100",
            "opening_hours": "Mon-Sun 07:30-19:00",
            "latitude": -17.8296,
            "longitude": 31.0506,
            "provider": "EcoCash",
        },
        {
            "name": "OneMoney Agent - Ximex Mall",
            "address": "Ximex Mall, Bulawayo CBD",
            "contact": "+263 713 200 200",
            "opening_hours": "Mon-Sat 08:00-18:00",
            "latitude": -20.1509,
            "longitude": 28.5859,
            "provider": "OneMoney",
        },
        {
            "name": "InnBucks Agent - TM Avondale",
            "address": "TM Pick n Pay Avondale, Harare",
            "contact": "+263 783 300 300",
            "opening_hours": "Mon-Sun 08:00-20:00",
            "latitude": -17.8012,
            "longitude": 31.0421,
            "provider": "InnBucks",
        },
    ],
    "innbucks_outlet": [
        {
            "name": "InnBucks Outlet - Joina City",
            "address": "Joina City, Cnr Jason Moyo & Julius Nyerere, Harare",
            "contact": "+263 783 300 310",
            "opening_hours": "Mon-Sat 08:00-18:00",
            "latitude": -17.8248,
            "longitude": 31.0457,
            "provider": "InnBucks",
        },
        {
            "name": "InnBucks Outlet - Eastgate",
            "address": "Eastgate Mall, Robert Mugabe Rd, Harare",
            "contact": "+263 783 300 311",
            "opening_hours": "Mon-Sat 08:00-18:00",
            "latitude": -17.8269,
            "longitude": 31.0560,
            "provider": "InnBucks",
        },
        {
            "name": "InnBucks Outlet - Bulawayo",
            "address": "Fife Street, Bulawayo CBD",
            "contact": "+263 783 300 312",
            "opening_hours": "Mon-Sat 08:00-17:30",
            "latitude": -20.1515,
            "longitude": 28.5835,
            "provider": "InnBucks",
        },
    ],
    "telecash_shop": [
        {
            "name": "Telecash Shop - Harare CBD",
            "address": "Nelson Mandela Ave, Harare CBD",
            "contact": "+263 732 100 100",
            "opening_hours": "Mon-Fri 08:00-17:00",
            "latitude": -17.8312,
            "longitude": 31.0470,
            "provider": "Telecash",
        },
        {
            "name": "Telecash Shop - Eastgate",
            "address": "Eastgate Mall, Robert Mugabe Rd, Harare",
            "contact": "+263 732 100 101",
            "opening_hours": "Mon-Sat 08:00-18:00",
            "latitude": -17.8271,
            "longitude": 31.0558,
            "provider": "Telecash",
        },
        {
            "name": "Telecash Shop - Bulawayo",
            "address": "Leopold Takawira Ave, Bulawayo CBD",
            "contact": "+263 732 100 102",
            "opening_hours": "Mon-Fri 08:00-17:00",
            "latitude": -20.1545,
            "longitude": 28.5848,
            "provider": "Telecash",
        },
    ],
    "agency_banking": [
        {
            "name": "OK Zimbabwe - Avondale (Agency Banking)",
            "address": "King George Rd, Avondale, Harare",
            "contact": "+263 242 334 500",
            "opening_hours": "Mon-Sun 08:00-20:00",
            "latitude": -17.7970,
            "longitude": 31.0420,
            "provider": "OK Zimbabwe",
        },
        {
            "name": "TM Pick n Pay - Sam Levy's (Agency Banking)",
            "address": "Sam Levy's Village, Borrowdale, Harare",
            "contact": "+263 242 882 600",
            "opening_hours": "Mon-Sun 08:00-20:00",
            "latitude": -17.7620,
            "longitude": 31.0852,
            "provider": "TM Pick n Pay",
        },
        {
            "name": "Spar - Bulawayo Central (Agency Banking)",
            "address": "Fife Street, Bulawayo CBD",
            "contact": "+263 292 260 300",
            "opening_hours": "Mon-Sun 08:00-19:00",
            "latitude": -20.1530,
            "longitude": 28.5842,
            "provider": "Spar",
        },
    ],
}
